---
  - name: Ansible Network Device Inventory
    hosts: localhost
    connection: local
    gather_facts: false
    vars_files:
      - credentials.yml
      - params.yml
    vars:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{username}}"
      dnac_password: "{{password}}"
      ## VAR extractions
      SiteNameHierarchy: "{{SiteNameHierarchy}}"
      deviceFamily: "{{deviceFamily}}"
      localOutputFile: "{{localOutputFile}}"
      ##
      dnac_login: &dnac_login
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_version: 2.2.2.3
        dnac_verify: False
        dnac_debug: False

    tasks:
    - name: Get start timestamp from the system
      shell: "date +%Y-%m-%dT%H-%M-%S"
      register: timestamp
      delegate_to: localhost

    - name: Print playbook start timestamp
      ansible.builtin.debug:
        msg: "Playbook start time: {{timestamp.stdout}}"

    - name: Device list output file
      ansible.builtin.debug:
        msg: "Device list output file: {{localOutputFile}}"

    - name: Read Site SiteNameHierarchy
      ansible.builtin.debug:
        msg: "Playbook end time: {{SiteNameHierarchy}}"

    - name: Get Site Id
      cisco.dnac.site_info:
        <<: *dnac_login
        name: "{{SiteNameHierarchy}}"
      register: Site_Detail

    - name: Site Id
      set_fact:
          siteId: "{{Site_Detail.dnac_response.response[0].id}}"

    - name: Gather membership info
      cisco.dnac.site_membership_info:
        <<: *dnac_login
        siteId: "{{siteId}}"
        deviceFamily: "{{item}}"
      register: membership_info
      with_items: "{{deviceFamily}}"
      no_log: true

    - name: Initialize Device List
      set_fact:
        device_list: []

    - name: Display membership info
      set_fact:
        device_list: "{{ device_list + item.1.response }}"
      when: item.1.response|length > 0
      with_subelements: 
         - "{{membership_info.results}}"
         - dnac_response.device
      loop_control:
        label: "{{item.1.response}}"
      no_log: true

    - name: Write out to local file
      local_action: copy content="{{device_list}}" dest="{{localOutputFile}}"

    - name: Get end timestamp from the system
      shell: "date +%Y-%m-%dT%H-%M-%S"
      register: timestamp
      delegate_to: localhost

    - name: Print timestamp
      ansible.builtin.debug:
        msg: "Playbook end time: {{timestamp.stdout}}"