---
  - name: Ansible Network Device Inventory
    hosts: localhost
    connection: local
    gather_facts: false
    vars_files:
      - credentials.yml
      - params.yml
    vars:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{username}}"
      dnac_password: "{{password}}"
      deviceFamily: "{{deviceFamily}}"
      siteId: "d88cc44e-9b5e-4bd7-9df1-c96afa7a38a9"
      dnac_login: &dnac_login
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_version: 2.2.2.3
        dnac_verify: False
        dnac_debug: False

    tasks:
    - name: Get start timestamp from the system
      shell: "date +%Y-%m-%dT%H-%M-%S"
      register: timestamp
      delegate_to: localhost

    - name: Print playbook start timestamp
      ansible.builtin.debug:
        msg: "Playbook start time: {{timestamp.stdout}}"

    - name: Gather membership info
      cisco.dnac.site_membership_info:
        <<: *dnac_login
        siteId: "{{siteId}}"
        deviceFamily: "{{item}}"
      register: membership_info
      with_items: "{{deviceFamily}}"
      no_log: true

    - name: Iterate over devices
      ansible.builtin.debug:
        msg: "{{item}}"
      with_items: "{{membership_info.results}}"
      ## prevent verbose output of each item contents
      loop_control:
        label: ""

    - name: Display membership info
      ansible.builtin.debug:
        msg: "{{item}}"
      with_subelements: 
         - "{{membership_info.results}}"
         - dnac_response.device


    # - name: Display membership info
    #   ansible.builtin.debug:
    #     #msg: "{{membership_info.dnac_response.device}}"
    #     msg: "{{membership_info}}"

    - name: Get end timestamp from the system
      shell: "date +%Y-%m-%dT%H-%M-%S"
      register: timestamp
      delegate_to: localhost

    - name: Print timestamp
      ansible.builtin.debug:
        msg: "Playbook end time: {{timestamp.stdout}}"